spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    group-id: group_id
    auto-offset-reset: earliest
    properties:
      security:
        protocol: PLAINTEXT
      sasl:
        mechanism: GSSAPI
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="" password="";

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  numberFrom: ${TWILIO_NUMBER_FROM}
  numberTo: ${TWILIO_NUMBER_TO}

