apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: kafka-monorepo-consumer
          image: control11/kafka-monorepo-consumer:latest
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: consumer-secret
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consumer-secret
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_NUMBER_FROM
              valueFrom:
                secretKeyRef:
                  name: consumer-secret
                  key: TWILIO_NUMBER_FROM
            - name: TWILIO_NUMBER_TO
              valueFrom:
                secretKeyRef:
                  name: consumer-secret
                  key: TWILIO_NUMBER_TO
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: consumer