name: Build, Test, and Push Docker Images


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-20.04.06

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Applications
      run: |
        ./gradlew clean build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push producer image
      uses: docker/build-push-action@v2
      with:
        context: ./producer
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/producer:latest

    - name: Build and push consumer image
      uses: docker/build-push-action@v2
      with:
        context: ./consumer
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/consumer:latest
