name: Build, Test, and Push Docker Images


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'


    - name: Build Producer Application
      run: |
        cd producer
        chmod +x gradlew
        ./gradlew clean build
        

    - name: Build Consumer Application
      run: |
        cd consumer
        chmod +x gradlew
        ./gradlew clean build

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push producer image
      uses: docker/build-push-action@v2
      with:
        context: ./producer
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/producer:latest

    - name: Build and push consumer image
      uses: docker/build-push-action@v2
      with:
        context: ./consumer
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/consumer:latest
